In [ ]:
from scipy.stats import chisquare
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 1.데이터1

In [ ]:
df_2 = pd.read_csv('/content/drive/MyDrive/jeju_raw_data/tourist_info.csv')

In [ ]:
df_2['테마'][0]

'#섬속의섬 #경관/포토 #아이\n#맑음 #자연경관 #포토스팟 #어린이 #봄꽃 #유채꽃 #유네스코'

In [ ]:
arr = '#섬속의섬 #경관/포토 #아이#맑음 #자연경관 #포토스팟 #어린이 #봄꽃 #유채꽃 #유네스코'
arr = arr.replace(' ','')
arr = arr.split('#')
arr = arr[1:]
arr

['섬속의섬', '경관/포토', '아이', '맑음', '자연경관', '포토스팟', '어린이', '봄꽃', '유채꽃', '유네스코']

In [ ]:
arr = []
for i in df_2['테마']:
  i = i.replace(' ','')
  i = i.replace('\n','')
  arr.append(i.split('#')[1:])
df_2['테마'] = arr
df_2.head()

Unnamed: 0   관광 명소                           주소  \
0           0      우도     제주특별자치도 제주시 우도면 삼양고수물길 1   
1           1   성산일출봉  제주특별자치도 서귀포시 성산읍 일출로 284-12   
2           2   사려니숲길  제주특별자치도 제주시 조천읍 교래리 산 137-1   
3           3   카멜리아힐          제주 서귀포시 안덕면 병악로 166   
4           4  협재해수욕장   제주특별자치도 제주시 한림읍 한림로 329-10   

                                                  테마  
0  [섬속의섬, 경관/포토, 아이, 맑음, 자연경관, 포토스팟, 어린이, 봄꽃, 유채꽃...  
1              [일출, 오름, 경관/포토, 부모, 자연경관, 포토스팟, 유네스코]  
2  [숲길, 걷기/등산, 친구, 커플, 흐림, 봄, 자연경관, 도보여행, 도보, 숲, 단풍]  
3  [경관/포토, 커플, 아이, 맑음, 겨울, 힐링, 우수관광사업체, 자연경관, 포토스...  
4  [일몰, 해수욕장, 액티비티, 아이, 맑음, 여름, 자연경관, 체험, 레저/체험, ...

In [ ]:
index_list = []
for i, v in enumerate(df_2['테마']):
  if '전통' in v:
    index_list.append(i)
index_list

[]

# 2.데이터 정리

## 1.여행테마

### 1-1. 역사테마 history

In [ ]:
history = []
hist = ['4.3', '너븐숭이', '문화', '문화관광', '문화유적지', '역사유적', '신나락만나락', '사찰', '절', '토기', 
        '제주4.3', '전통', '신화탐방로', '북촌','유적']

for i in df_2['테마']:
  result_1 = 0
  result_2 = 0
  result_3 = 0
  result_4 = 0
  result_list = []
  result = 0
  for j in i:
    if j in hist:
      if j == '문화' or j == '문화관광' or j == '문화유적지' or j == '전통':
        result_1 += 1
      elif j == '4.3' or j == '제주4.3' or j == '너븐숭이' or j == '북촌':
        result_2 += 1
      elif j == '신나락만나락' or j == '신화탐방로':
        result_3 += 1
      elif j == '역사유적' or j == '토기' or j == '유적':
        result_4 += 1
      else:
        result += 1
  
  result_list.append(result_1)
  result_list.append(result_2)
  result_list.append(result_3)
  result_list.append(result_4)

  for x in result_list:
    if x > 0:
      result += 1
  history.append(result)

print(set(history))
print(len(history))

{0, 1, 2, 3, 4}
1096


### 1-2. 미래테마 future 날림

In [ ]:
# future = []
# fut = '6차산업'
# for i in df_2['테마']:
#   if fut in i:
#     future.append(1)
#   else:
#     future.append(0)
# print(set(future))
# print(len(future))

### 1-3. 자연테마 nature

In [ ]:
# 밤은 보통 야경을 말하는 거 같아서 자연이라는 테마와 안 어울리는거 같아 뺐습니다. (차)
nature = []
nat = ['경관/포토', '생태', '생태문화', '야영장', '세계자연유산', '숲길', '캠핑장','일몰', 
       '일몰명소', '일출', '제주동백수목원', '코스모스', '자연경관', '체험전시', '유네스코', 
       '유채꽃', '폭포', '한옥', '효돈천', '캠핑', '해바라기', '계곡', '숲', '노천탕', 
       '오름', '동굴', '글램핑', '동백나무', '동백', '매화','억새','용천수']

for i in df_2['테마']:
  result_1 = 0
  result_2 = 0
  result_3 = 0
  result_4 = 0
  result_list = []
  result = 0
  for j in i:
    if j in nat:
      if j == '일몰' or j == '일몰명소' or j == '일출':
        result_1 += 1
      elif j == '경관/포토' or j == '생태' or j == '생태문화' or j == '세계자연유산' or j == '자연경관'\
       or j == '유네스코':
        result_2 += 1
      elif j == '야영장' or j == '캠핑장' or j == '캠핑' or j == '글램핑':
        result_3 += 1
      elif j == '제주동백수목원' or j == '동백나무' or j == '동백':
        result_4 += 1
      else:
        result += 1
  
  result_list.append(result_1)
  result_list.append(result_2)
  result_list.append(result_3)
  result_list.append(result_4)

  for x in result_list:
    if x > 0:
      result += 1
  nature.append(result)
print(set(nature))
print(len(nature))

{0, 1, 2, 3, 4, 5}
1096


### 1-4. 포토테마 photo

In [ ]:
photo = []
pho = ['커플스냅', '우정스냅', '포토스팟']
for i in df_2['테마']:
  result = 0
  for j in i:
    if j in pho:
      result += 1
  photo.append(result)
print(set(photo))
print(len(photo))

{0, 1, 2}
1096


### 1-5. 도보여행테마 walk

In [ ]:
walk = []
dobo = ['도보','도보여행', '마을산책', '마을관광', '산책로']

for i in df_2['테마']:
  result_1 = 0
  result_2 = 0
  result_3 = 0
  result_list = []
  result = 0
  for j in i:
    if j in dobo:
      if j == '도보' or j == '도보여행':
        result_1 += 1
      elif j == '마을관광' or j == '마을산책':
        result_2 += 1
      elif j == '산책로':
        result_3 += 1
  result_list.append(result_1)
  result_list.append(result_2)
  result_list.append(result_3)

  for x in result_list:
    if x > 0:
      result += 1
  walk.append(result)
print(set(walk))
print(len(walk))

{0, 1, 2}
1096


### 1-6. 예술테마 art

In [ ]:
art = []
ar = ['미술관', '미술/박물관', '미술', '미디어아트', '예술', '아트', '전시', '전시/행사',
      '전시관', '전시와행사', '뮤지컬', '연극']

for i in df_2['테마']:
  result_1 = 0
  result_2 = 0
  result_list = []
  result = 0
  for j in i:
    if j in ar:
      if j == '미술관' or j == '미술/박물관' or j == '전시' or j == '전시/행사' or j == '전시관'\
       or j == '전시와행사':
        result_1 += 1
      elif j == '미술' or j == '예술' or j == '미디어아트' or j == '아트':
        result_2 += 1
      else:
        result += 1
  
  result_list.append(result_1)
  result_list.append(result_2)

  for x in result_list:
    if x > 0:
      result += 1
  art.append(result)

print(set(art))
print(len(art))

{0, 1, 2}
1096


### 1-7.반려동물테마 pet 날림

In [ ]:
# pet = []
# pe = '애견동반'

# for i in df_2['테마']:
#   if pe in i:
#     pet.append(1)
#   else:
#     pet.append(0)
# print(set(pet))
# print(len(pet))

{0, 1}
1096


## 2.활동테마

### 2-1.육상활동 activity_landleisure

In [ ]:
activity_landleisure = []
al = ['ATV', '골프', '걷기/등산', '걷기', '내창트레킹', '농촌체험마을', '드라이브', '동물먹이주기', 
      '등산', '레이싱', '메디컬요가', '승마', '빈야사요가', '지질트레일', '요가', 
      '트레킹', '카트', '자전거', '체험', '체험관광', '체험여행', '테랍툴요가', 
      '플라잉요가', '하타요가', '체험', '해안산책', '테마파크', '테마공원', '어트랙션']

for i in df_2['테마']:
  result_1 = 0
  result_2 = 0
  result_3 = 0
  result_4 = 0
  result_list = []
  result = 0

  for j in i:
    if j in al:
      if j == '걷기/등산' or j == '내창트레킹' or j == '등산' or j == '트레킹' or j == '걷기'\
      or j == '지질트레일' or j == '해안산책':
        result_1 += 1
      elif j == '체험관광' or j == '체험여행' or j == '체험' or j == '농촌체험마을'\
       or j == '동물먹이주기':
        result_2 += 1
      elif j == '플라잉요가' or j == '하타요가' or j == '메디컬요가' or j == '빈야사요가'\
       or j == '요가':
        result_3 += 1
      elif j == '테마파크' or j == '테마공원' or j == '어트랙션':
        result_4 += 1
      else:
        result += 1
  
  result_list.append(result_1)
  result_list.append(result_2)
  result_list.append(result_3)
  result_list.append(result_4)

  for idx, val in enumerate(result_list):
    if idx == 3:
      result += val
    elif val > 0:
      result += 1
  activity_landleisure.append(result)

print(set(activity_landleisure))
print(len(activity_landleisure))

{0, 1, 2, 3, 4, 5}
1096


### 2-2.수상활동 activity_waterleisure

In [ ]:
activity_waterleisure = []
aw = ['waterleisure', '낚시', '다이빙체험', '마린스포츠', '물놀이', '바릇잡이', '스쿠버다이빙', '스쿠버교육', 
      '수상레저', '액티비티', '수영장', '차귀도유람선', '해상레저', '해양스포츠', '해수욕장', '해변',
      '패들요가']

for i in df_2['테마']:
  result_1 = 0
  result_2 = 0
  result_3 = 0
  result_4 = 0
  result_list = []
  result = 0
  for j in i:
    if j in aw:
      if j == 'waterleisure' or j == '수상레저':
        result_1 += 1
      elif j == '마린스포츠' or j == '물놀이' or j == '수영장':
        result_2 += 1
      elif j == '스쿠버다이빙' or j == '스쿠버교육' or j == '다이빙체험':
        result_3 += 1
      elif j == '해수욕장' or j == '해변':
        result_4 += 1
      else:
        result += 1
  
  result_list.append(result_1)
  result_list.append(result_2)
  result_list.append(result_3)
  result_list.append(result_4)
  for x in result_list:
    if x>0:
      result += 1
  activity_waterleisure.append(result)

print(set(activity_waterleisure))
print(len(activity_waterleisure))

{0, 1, 2, 3, 4}
1096


### 2-3.공중활동 activity_sky

In [ ]:
activity_sky = []
act_sky = '라이딩'

for i in df_2['테마']:
  if act_sky in i:
    activity_sky.append(1)
  else:
    activity_sky.append(0)

print(set(activity_sky))
print(len(activity_sky))

{0, 1}
1096


## 3.계절테마

### 3-1.봄 spring

In [ ]:
spring = []
spr = ['벚꽃', '봄', '봄꽃']

for i in df_2['테마']:
  result = 0
  for j in i:
    if j in spr:
      result = 1
  spring.append(result)
print(set(spring))
print(len(spring))

{0, 1}
1096


### 3-2.여름 summer

In [ ]:
summer = []
summ = '여름'

for i in df_2['테마']:
  if summ in i:
    summer.append(1)
  else:
    summer.append(0)

print(set(summer))
print(len(summer))

{0, 1}
1096


### 3-3 가을 fall

In [ ]:
fall = []
f = ['가을', '단풍']

for i in df_2['테마']:
  result = 0
  for j in i:
    if j in f:
      result = 1
  fall.append(result)
print(set(fall))
print(len(fall))

{0, 1}
1096


### 3-4 겨울 winter

In [ ]:
winter = []
win = '겨울'

for i in df_2['테마']:
  if win in i:
    winter.append(1)
  else:
    winter.append(0)

print(set(winter))
print(len(winter))

{0, 1}
1096


### 3-5 사계절 four_seasons

In [ ]:
four_seasons = []
fs = ['사게절', '사계절']

for i in df_2['테마']:
  result = 0
  for j in i:
    if j in fs:
      result = 1
  four_seasons.append(result)
print(set(four_seasons))
print(len(four_seasons))

{0, 1}
1096


## 4.연령층

### 4-1.노년 old

In [ ]:
old = []
ol = '노년'

for i in df_2['테마']:
  if ol in i:
    old.append(1)
  else:
    old.append(0)
print(set(old))
print(len(old))

{0, 1}
1096


### 4-2.어린이 children

In [ ]:
children = []
child = ['어린이', '아이']

for i in df_2['테마']:
  result = 0
  for j in i:
    if j in child:
      result = 1
  children.append(result)

print(set(children))
print(len(children))

{0, 1}
1096


### 4-3. 청년 youth

In [ ]:
youth = []
you = '청년'

for i in df_2['테마']:
  if you in i:
    youth.append(1)
  else:
    youth.append(0)

print(set(youth))
print(len(youth))

{0, 1}
1096


### 4-4.중년 middle_age

In [ ]:
middle_age = []
middle = '중/장년'

for i in df_2['테마']:
  if middle in i:
    middle_age.append(1)
  else:
    middle_age.append(0)

print(set(middle_age))
print(len(middle_age))

{0, 1}
1096


## 5.구헝원

### 5-1.가족 family

In [ ]:
family = []
fam = '가족'

for i in df_2['테마']:
  if fam in i:
    family.append(1)
  else:
    family.append(0)

print(set(family))
print(len(family))

{0, 1}
1096


### 5-2.부모 parents

In [ ]:
parents = []
par = '부모'

for i in df_2['테마']:
  if par in i:
    parents.append(1)
  else:
    parents.append(0)

print(set(parents))
print(len(parents))

{0, 1}
1096


### 5-3.커플 couple

In [ ]:
couple = []
cou = '커플'

for i in df_2['테마']:
  if cou in i:
    couple.append(1)
  else:
    couple.append(0)

print(set(couple))
print(len(couple))

{0, 1}
1096


### 5-4.친구 friend

In [ ]:
friend = []
fri = '친구'

for i in df_2['테마']:
  if fri in i:
    friend.append(1)
  else:
    friend.append(0)

print(set(friend))
print(len(friend))

{0, 1}
1096


### 5-5.혼자 alone

In [ ]:
alone = []
alo = '혼자'

for i in df_2['테마']:
  if alo in i:
    alone.append(1)
  else:
    alone.append(0)

print(set(alone))
print(len(alone))

{0, 1}
1096


## 6.장소 날림

### 6-1.계곡 valley

In [ ]:
# valley = []
# vall = '계곡'

# for i in df_2['테마']:
#   if vall in i:
#     valley.append(1)
#   else:
#     valley.append(0)

# print(set(valley))
# print(len(valley))

### 6-2.산 mountain

In [ ]:
# mountain = []
# mount = ['수월봉', '한라산']

# for i in df_2['테마']:
#   result = 0
#   for j in i:
#     if j in mount:
#       result += 1
#   mountain.append(result)

# print(set(mountain))
# print(len(mountain))

### 6-3.해변 beach

In [ ]:
# beach = []
# bea = [ '해수욕장', '해변산책', '해변']

# for i in df_2['테마']:
#   result = 0
#   for j in i:
#     if j in bea:
#       result += 1
#   beach.append(result)

# print(set(beach))
# print(len(beach))

### 6-4.공원 park

In [ ]:
# park = []
# par = ['곶자왈', '테마공원', '테마파크', '해거름마을공원']

# for i in df_2['테마']:
#   result = 0
#   for j in i:
#     if j in par:
#       result += 1
#   park.append(result)

# print(set(park))
# print(len(park))

### 6-5.온천 spa

In [ ]:
# spa = []
# sp = '노천탕'

# for i in df_2['테마']:
#   if sp in i:
#     spa.append(1)
#   else:
#     spa.append(0)

# print(set(spa))
# print(len(spa))

### 6-6.오름 oreum

In [ ]:
# oreum = []
# ore = ['금오름', '오름']

# for i in df_2['테마']:
#   result = 0
#   for j in i:
#     if j in ore:
#       result += 1
#   oreum.append(result)

# print(set(oreum))
# print(len(oreum))

### 6-7.동굴 cave

In [ ]:
# cave = []
# ca = '동굴'

# for i in df_2['테마']:
#   if ca in i:
#     cave.append(1)
#   else:
#     cave.append(0)

# print(set(cave))
# print(len(cave))

### 6-8.섬, 6-9 실내 보류
이유: 그곳에 많이 해당되는 곳이 아닌 그곳 자체를 목적지로 하기 때문

## 새로운 데이터 프레임 만들기

In [ ]:
student_card = pd.DataFrame([[20190103, 'Kim', 'H'],
                             [20190222, 'Lee', 'W'],
                             [20190531, 'Jeong', 'S']], columns = ['ID', 'name', 'class']) 

In [ ]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1096 entries, 0 to 1095
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  1096 non-null   int64 
 1   관광 명소       1095 non-null   object
 2   주소          1088 non-null   object
 3   테마          1096 non-null   object
dtypes: int64(1), object(3)
memory usage: 34.4+ KB


In [ ]:
df = pd.DataFrame()

In [ ]:
column_data = [history, nature, photo, walk, art, activity_landleisure, activity_waterleisure,
           activity_sky,spring,summer,fall,winter,four_seasons, old, children,youth,middle_age,
           family,parents,couple,friend,alone]
name_list = ['history', 'nature', 'photo', 'walk', 'art', 'activity_landleisure',
             'activity_waterleisure', 'activity_sky','spring','summer','fall','winter','four_seasons',
             'old', 'children', 'youth', 'middle_age', 'family','parents','couple','friend','alone']
df['관광명소'] = list(df_2['관광 명소'])
df['주소'] = list(df_2['주소'])

for i,j in zip(name_list, column_data):
  print(i)
  df[i] = j

history
nature
photo
walk
art
activity_landleisure
activity_waterleisure
activity_sky
spring
summer
fall
winter
four_seasons
old
children
youth
middle_age
family
parents
couple
friend
alone


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1096 entries, 0 to 1095
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   관광명소                   1095 non-null   object
 1   주소                     1088 non-null   object
 2   history                1096 non-null   int64 
 3   nature                 1096 non-null   int64 
 4   photo                  1096 non-null   int64 
 5   walk                   1096 non-null   int64 
 6   art                    1096 non-null   int64 
 7   activity_landleisure   1096 non-null   int64 
 8   activity_waterleisure  1096 non-null   int64 
 9   activity_sky           1096 non-null   int64 
 10  spring                 1096 non-null   int64 
 11  summer                 1096 non-null   int64 
 12  fall                   1096 non-null   int64 
 13  winter                 1096 non-null   int64 
 14  four_seasons           1096 non-null   int64 
 15  old                  

In [ ]:
df.head(1)

In [ ]:
# 697 : 제주특별자치도 제주시 조천읍 남조로 1660
# 714 : 제주특별자치도 제주시 구좌읍 구좌해안로 237
# 758 : 제주특별자치도 제주시 우도면 연평리 3
# 778 : 제주시 애월읍 봉성리 4554-20
# 791 : 제주특별자치도 서귀포시 안덕면 상천리 산22
# 843 : 제주도 서귀포시 남원읍 수망리 59
# 908 : 제주특별자치도 서귀포시 안덕면 감산리 1144
# 1018 : 추자도

In [ ]:
df.head(1)

In [ ]:
idx_list = [697, 714, 758, 778, 791, 843, 908, 1018]
name_list = ['제주특별자치도 제주시 조천읍 남조로 1660', '제주특별자치도 제주시 구좌읍 구좌해안로 237',
             '제주특별자치도 제주시 우도면 연평리 3', '제주시 애월읍 봉성리 4554-20',
             '제주특별자치도 서귀포시 안덕면 상천리 산22', '제주도 서귀포시 남원읍 수망리 59',
             '제주특별자치도 서귀포시 안덕면 감산리 1144', '추자도']

for i, v in zip(idx_list, name_list):
  df['주소'][i] = v

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
# 578 : 애월 바다
df['관광명소'][578] = '애월바다'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1096 entries, 0 to 1095
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   관광명소                   1096 non-null   object
 1   주소                     1096 non-null   object
 2   history                1096 non-null   int64 
 3   nature                 1096 non-null   int64 
 4   photo                  1096 non-null   int64 
 5   walk                   1096 non-null   int64 
 6   art                    1096 non-null   int64 
 7   activity_landleisure   1096 non-null   int64 
 8   activity_waterleisure  1096 non-null   int64 
 9   activity_sky           1096 non-null   int64 
 10  spring                 1096 non-null   int64 
 11  summer                 1096 non-null   int64 
 12  fall                   1096 non-null   int64 
 13  winter                 1096 non-null   int64 
 14  four_seasons           1096 non-null   int64 
 15  old                  

In [ ]:
df.to_csv('jeju_train_final.csv')

## 데이터 받기

In [45]:
from scipy.stats import chisquare
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [46]:
df = pd.read_excel('/content/drive/MyDrive/jeju/training_tourist_data.xlsx',index_col=0)

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Float64Index: 1097 entries, 0.0 to nan
Data columns (total 24 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   관광 명소   1092 non-null   object 
 1   주소      1093 non-null   object 
 2   역사      1092 non-null   float64
 3   자연      1092 non-null   float64
 4   사진      1092 non-null   float64
 5   도보      1092 non-null   float64
 6   예술      1092 non-null   float64
 7   육상      1092 non-null   float64
 8   수상      1092 non-null   float64
 9   공중      1092 non-null   float64
 10  봄       1092 non-null   float64
 11  여름      1092 non-null   float64
 12  가을      1092 non-null   float64
 13  겨울      1092 non-null   float64
 14  사계절     1092 non-null   float64
 15  어린이     1092 non-null   float64
 16  청년      1092 non-null   float64
 17  중년      1092 non-null   float64
 18  노년      1092 non-null   float64
 19  혼자      1092 non-null   float64
 20  친구      1092 non-null   float64
 21  커플      1092 non-null   float64
 2

In [48]:
df.tail(6)

관광 명소                        주소   역사   자연   사진   도보   예술   육상   수상  \
1091.0    휴림  제주특별자치도 제주시 애월읍 광령남서길 40  0.0  1.0  0.0  0.0  0.0  2.0  1.0   
NaN      NaN                       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
NaN      NaN                       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
NaN      NaN                       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
NaN      NaN                       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
NaN      NaN                            NaN  NaN  NaN  NaN  NaN  NaN  NaN   

         공중  ...  사계절  어린이   청년   중년   노년   혼자   친구   커플   부모   가족  
1091.0  0.0  ...  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  
NaN     NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
NaN     NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
NaN     NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
NaN     NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
NaN     NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  

[6 rows x 24 columns]

In [49]:
df.dropna(axis = 0, inplace = True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Float64Index: 1092 entries, 0.0 to 1091.0
Data columns (total 24 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   관광 명소   1092 non-null   object 
 1   주소      1092 non-null   object 
 2   역사      1092 non-null   float64
 3   자연      1092 non-null   float64
 4   사진      1092 non-null   float64
 5   도보      1092 non-null   float64
 6   예술      1092 non-null   float64
 7   육상      1092 non-null   float64
 8   수상      1092 non-null   float64
 9   공중      1092 non-null   float64
 10  봄       1092 non-null   float64
 11  여름      1092 non-null   float64
 12  가을      1092 non-null   float64
 13  겨울      1092 non-null   float64
 14  사계절     1092 non-null   float64
 15  어린이     1092 non-null   float64
 16  청년      1092 non-null   float64
 17  중년      1092 non-null   float64
 18  노년      1092 non-null   float64
 19  혼자      1092 non-null   float64
 20  친구      1092 non-null   float64
 21  커플      1092 non-null   float64

## 데이터 전처리

In [50]:
address_list = list(set(df['주소']))
len(set(df['주소']))

1029

In [51]:
name_list = list(set(df['관광 명소']))
len(set(df['관광 명소']))

1092

In [52]:
# target -> 관광 명소
df_train = df.copy()
df_train = df_train.drop(['주소'], axis = 1)
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Float64Index: 1092 entries, 0.0 to 1091.0
Data columns (total 23 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   관광 명소   1092 non-null   object 
 1   역사      1092 non-null   float64
 2   자연      1092 non-null   float64
 3   사진      1092 non-null   float64
 4   도보      1092 non-null   float64
 5   예술      1092 non-null   float64
 6   육상      1092 non-null   float64
 7   수상      1092 non-null   float64
 8   공중      1092 non-null   float64
 9   봄       1092 non-null   float64
 10  여름      1092 non-null   float64
 11  가을      1092 non-null   float64
 12  겨울      1092 non-null   float64
 13  사계절     1092 non-null   float64
 14  어린이     1092 non-null   float64
 15  청년      1092 non-null   float64
 16  중년      1092 non-null   float64
 17  노년      1092 non-null   float64
 18  혼자      1092 non-null   float64
 19  친구      1092 non-null   float64
 20  커플      1092 non-null   float64
 21  부모      1092 non-null   float64

In [53]:
name_dict = {}
for i, val in enumerate(df_train['관광 명소']):
  name_dict[i] = val

In [54]:
name_dict[2]

'사려니숲길'

In [55]:
df_train.head()

관광 명소   역사   자연   사진   도보   예술   육상   수상   공중    봄  ...  사계절  어린이   청년  \
0.0      우도  0.0  2.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  1.0  0.0   
1.0   성산일출봉  0.0  3.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2.0   사려니숲길  0.0  3.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   
3.0   카멜리아힐  0.0  2.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  1.0  0.0   
4.0  협재해수욕장  0.0  3.0  0.0  0.0  0.0  1.0  4.0  0.0  0.0  ...  0.0  1.0  0.0   

      중년   노년   혼자   친구   커플   부모   가족  
0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
2.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  
3.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  
4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 23 columns]

In [56]:
for idx, _ in enumerate(df['관광 명소']):
  df_train['관광 명소'][idx] = idx

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [57]:
df_train.rename(columns = {'관광 명소':'target'},inplace=True)

In [58]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Float64Index: 1092 entries, 0.0 to 1091.0
Data columns (total 23 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   target  1092 non-null   object 
 1   역사      1092 non-null   float64
 2   자연      1092 non-null   float64
 3   사진      1092 non-null   float64
 4   도보      1092 non-null   float64
 5   예술      1092 non-null   float64
 6   육상      1092 non-null   float64
 7   수상      1092 non-null   float64
 8   공중      1092 non-null   float64
 9   봄       1092 non-null   float64
 10  여름      1092 non-null   float64
 11  가을      1092 non-null   float64
 12  겨울      1092 non-null   float64
 13  사계절     1092 non-null   float64
 14  어린이     1092 non-null   float64
 15  청년      1092 non-null   float64
 16  중년      1092 non-null   float64
 17  노년      1092 non-null   float64
 18  혼자      1092 non-null   float64
 19  친구      1092 non-null   float64
 20  커플      1092 non-null   float64
 21  부모      1092 non-null   float64

In [59]:
df_train.tail()

target   역사   자연   사진   도보   예술   육상   수상   공중    봄  ...  사계절  어린이  \
1087.0   1087  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0   
1088.0   1088  0.0  2.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1089.0   1089  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1090.0   1090  0.0  0.0  0.0  0.0  0.0  2.0  0.0  0.0  0.0  ...  0.0  0.0   
1091.0   1091  0.0  1.0  0.0  0.0  0.0  2.0  1.0  0.0  0.0  ...  0.0  1.0   

         청년   중년   노년   혼자   친구   커플   부모   가족  
1087.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1088.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1089.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1090.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1091.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  

[5 rows x 23 columns]

# 3.학습모델(ASL)

## 1.학습 파라미터 초기화

In [108]:
# 논문에서 가장 좋은 값을 낸다고 함 (40, 200, 40)
r_lambda = 40
nf = 200
alpha = 100 # 커진 α로 인해 r_ui값이 있는 c_ui와 없는 c_ui의 차이가 커진다.

## 2.학습 행렬 만들기

In [27]:
R = df_train.iloc[:,1:].values
R

array([[0., 2., 1., ..., 0., 0., 0.],
       [0., 3., 1., ..., 0., 1., 0.],
       [0., 3., 0., ..., 1., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 1., 0.]])

## 3.사용자와 아이템의 latent factor matrix 초기화

In [28]:
nu = R.shape[0]
ni = R.shape[1]

# initialize X and Y with very small values
X = np.random.rand(nu, nf) * 0.01 # latent user matrix
Y = np.random.rand(ni, nf) * 0.01 # latent item matrix
print(X)

[[6.68258798e-03 8.93395566e-03 7.53179198e-03 ... 3.12990199e-03
  9.29589333e-03 1.02852497e-04]
 [3.54152088e-03 6.85598586e-03 2.69775206e-04 ... 5.16673768e-03
  2.52256576e-03 3.51399262e-03]
 [7.02501185e-03 5.57544677e-03 8.60633706e-03 ... 7.14037105e-03
  1.06911026e-03 1.48231116e-03]
 ...
 [6.30669169e-03 7.74351563e-03 7.72115024e-05 ... 5.42852069e-04
  4.03082363e-03 8.93363810e-03]
 [8.62619734e-03 6.45448838e-03 8.41074340e-03 ... 7.82696436e-03
  1.52009486e-03 3.74380383e-04]
 [2.84182385e-03 9.45925851e-03 5.20082076e-03 ... 4.75666634e-03
  4.06675353e-03 4.92181446e-03]]


## 4.선호도 설정 P

In [29]:
P = np.copy(R)
P[P > 0] = 1
print(P)

[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 1. 0.]
 [0. 1. 0. ... 1. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 1. 1. 0.]]


## 5.신뢰도 설정 C

In [109]:
C = 1 + alpha * R
print(C)
print(C.shape)

[[  1. 201. 101. ...   1.   1.   1.]
 [  1. 301. 101. ...   1. 101.   1.]
 [  1. 301.   1. ... 101.   1.   1.]
 ...
 [101.   1.   1. ...   1.   1.   1.]
 [  1.   1.   1. ...   1.   1.   1.]
 [  1. 101.   1. ... 101. 101.   1.]]
(1092, 22)


## 6.Loss Function
- C: confidence matrix
- P: binary rating matrix
- X: user latent matrix
- Y: item latente matrix
- r_lambda: regularization lambda
- xTy: predicted matrix
- total_loss = (confidence_level * predict_loss) + regularization_loss

In [74]:
def loss_function(C, P, xTy, X, Y, r_lambda):
  predict_error = np.square(R - xTy)
  confidence_error = np.sum(C * predict_error)
  regularzation = r_lambda * ((np.sum(np.square(X))) + np.sum(np.square(Y)))
  total_loss = confidence_error + regularzation
  return np.sum(predict_error), confidence_error, regularzation, total_loss

## 7.Optimizer 설정



<img src = "https://drive.google.com/uc?id=17h4AasSq3oiKf7S8W-20XeodvvJyv4Zi" height = 200 width = 500>

In [69]:
# item latent matrix 고정
# nu = R.shape[0]
def optimize_user(X, Y, C, P, nu, nf, r_lambda):
  yT = np.transpose(Y)
  for u in range(nu):
    Cu = np.diag(C[u]) # diagonal_matrix
    yT_Cu_y = np.matmul(np.matmul(yT, Cu), Y)
    li = np.dot(r_lambda, np.identity(nf))
    yT_Cu_pu = np.matmul(np.matmul(yT, Cu), R[u])
    X[u] = np.linalg.solve(yT_Cu_y + li, yT_Cu_pu)

In [70]:
# user latent matrix 고정
# ni = R.shape[1]
def optimize_item(X, Y, C, P, ni, nf, r_lambda):
  xT = np.transpose(X)
  for i in range(ni):
    Ci = np.diag(C[:, i])
    xT_Ci_x = np.matmul(np.matmul(xT, Ci), X)
    li = np.dot(r_lambda, np.identity(nf))
    xT_Ci_pi = np.matmul(np.matmul(xT, Ci), R[:, i])
    Y[i] = np.linalg.solve(xT_Ci_x + li, xT_Ci_pi)

## 8-1.학습

In [35]:
X.shape

(1092, 200)

In [36]:
Y.shape

(22, 200)

In [110]:
predict_errors = []
confidence_errors = []
regularization_list = []
total_losses = []

for i in range(17):
  if i!=0:
    optimize_user(X, Y, C, P, nu, nf, r_lambda)
    optimize_item(X, Y, C, P, ni, nf, r_lambda)
  predict = np.matmul(X, np.transpose(Y))
  predict_error, confidence_error, regularization, total_loss = loss_function(C, P, predict, X, Y, r_lambda)
  
  predict_errors.append(predict_error)
  confidence_errors.append(confidence_error)
  regularization_list.append(regularization)
  total_losses.append(total_loss)

  print('--------------------step %d------------------------------' % i)
  print('predict error: %f' % predict_error)
  print('confidence error: %f' % confidence_error)
  print('regularization: %f' % regularization)
  print('total loss: %f' % total_loss)

predict = np.matmul(X, np.transpose(Y))
print('final predict')
print([predict])

--------------------step 0------------------------------
predict error: 1297.555783
confidence error: 6614.563266
regularization: 18333.503219
total loss: 24948.066486
--------------------step 1------------------------------
predict error: 1408.641515
confidence error: 1690.716308
regularization: 20098.493180
total loss: 21789.209487
--------------------step 2------------------------------
predict error: 1345.226682
confidence error: 1594.249623
regularization: 20129.331078
total loss: 21723.580702
--------------------step 3------------------------------
predict error: 1308.713076
confidence error: 1554.714210
regularization: 20143.246420
total loss: 21697.960630
--------------------step 4------------------------------
predict error: 1288.768894
confidence error: 1535.996636
regularization: 20147.463200
total loss: 21683.459836
--------------------step 5------------------------------
predict error: 1277.807563
confidence error: 1526.980694
regularization: 20147.280732
total loss: 21674

In [111]:
print(predict[0])
print(R[0])

[ 2.28101661e-01  1.99304916e+00  9.77080369e-01  4.20159059e-01
  2.20401790e-02  4.81961792e-01  1.59051919e-01 -3.29883273e-02
  9.78434738e-01  4.06964805e-01  4.13356121e-01  3.23710312e-01
  2.26348921e-01  9.66368029e-01  8.43586689e-02  8.40353462e-02
  7.87948210e-02  3.98202507e-01  7.87948210e-02  5.60265970e-01
  5.61386750e-01 -1.88586183e-04]
[0. 2. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


In [112]:
# predict = X @ Y.T
a = np.matmul(X, np.transpose(Y))
b = np.array(a == predict)
shape_1 = b.shape
arr = []
cnt = 0
b = b.astype('object')
for i in range(shape_1[0]):
  for x in b[i]:
      if len(arr) > 0 and arr[-1] != x:
        cnt += 1
      arr.append(x)
print(cnt)

0


In [40]:
# cos유사도
def compute_cos_similarity(v1, v2):
  norm1 = np.sqrt(np.sum(np.square(v1)))
  norm2 = np.sqrt(np.sum(np.square(v2)))
  dot = np.dot(v1, v2)
  return dot / (norm1 * norm2)

In [125]:
# 유사한 데이터 찾기 predict_matrix
my_id, my_vector = 10, predict[10]
best_match, best_match_id, best_match_vector = -1, -1, []
similar_user_predict = []
for user_id, user_vector in enumerate(predict):
  if my_id != user_id:
    cos_similarity = compute_cos_similarity(my_vector, user_vector)
    if cos_similarity > -1:
      similar_user_predict.append([cos_similarity, user_id])
    if cos_similarity > best_match:
      best_match = cos_similarity
      best_match_id = user_id
      best_match_vector = user_vector
print('Best Match: {}, Best Match ID: {}'.format(best_match, best_match_id))

Best Match: 0.9819175167960483, Best Match ID: 328


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in double_scalars
  


In [126]:
similar_user_predict.sort(key=lambda x:-x[0])
similar_user_predict[:11]

[[0.9819175167960483, 328],
 [0.9780856173552879, 239],
 [0.9628475835566234, 252],
 [0.9558299313212427, 177],
 [0.9558299313212427, 242],
 [0.9549654101865994, 345],
 [0.9548489054813095, 931],
 [0.9548489054813095, 957],
 [0.9506536875635627, 369],
 [0.948564721081719, 314],
 [0.948564721081719, 950]]

In [127]:
arr_1 = []
for i in df_train.iloc[10,:]:
  arr_1.append(i)
arr_2 = []
for i in df_train.iloc[328,:]:
  arr_2.append(i)

print(arr_1[1:])
print(arr_2[1:])
print(name_dict[10])
print(name_dict[328])

[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0]
[0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0]
오설록티뮤지엄
조함해안도로


In [129]:
# 내가 필요한 것 latent_user_matrix
my_id, my_vector = 10, X[10]
best_match, best_match_id, best_match_vector = -1, -1, []
similar_user_X = []
for user_id, user_vector in enumerate(X):
  if my_id != user_id:
    cos_similarity = compute_cos_similarity(my_vector, user_vector)
    if cos_similarity > -1:
      similar_user_X.append([cos_similarity, user_id])
    if cos_similarity > best_match:
      best_match = cos_similarity
      best_match_id = user_id
      best_match_vector = user_vector
print('Best Match: {}, Best Match ID: {}'.format(best_match, best_match_id))

Best Match: 0.9766197275931873, Best Match ID: 328


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in double_scalars
  


In [130]:
similar_user_X.sort(key=lambda x:-x[0])
similar_user_X[:11]

[[0.9766197275931873, 328],
 [0.9738639675958497, 239],
 [0.9482513737772156, 177],
 [0.9482513737772156, 242],
 [0.9137923871941863, 931],
 [0.9137923871941863, 957],
 [0.8730673140914961, 463],
 [0.8730673140914961, 758],
 [0.872383179200062, 488],
 [0.86751502696144, 252],
 [0.8607137398546888, 712]]

In [131]:
# 내가 필요한 것 R
my_id, my_vector = 10, R[10]
best_match, best_match_id, best_match_vector = -1, -1, []
similar_user_R = []
for user_id, user_vector in enumerate(R):
  if my_id != user_id:
    cos_similarity = compute_cos_similarity(my_vector, user_vector)
    if cos_similarity > -1:
      similar_user_R.append([cos_similarity, user_id])
    if cos_similarity > best_match:
      best_match = cos_similarity
      best_match_id = user_id
      best_match_vector = user_vector
print('Best Match: {}, Best Match ID: {}'.format(best_match, best_match_id))

Best Match: 0.9486832980505138, Best Match ID: 931


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in double_scalars
  


In [132]:
similar_user_R.sort(key=lambda x:-x[0])
similar_user_R[:11]

[[0.9486832980505138, 931],
 [0.9486832980505138, 957],
 [0.9128709291752769, 252],
 [0.9128709291752769, 328],
 [0.8944271909999159, 239],
 [0.8944271909999159, 712],
 [0.8944271909999159, 886],
 [0.8485281374238569, 673],
 [0.8485281374238569, 960],
 [0.8451542547285165, 61],
 [0.8451542547285165, 345]]

In [133]:
# 내적값 크기 predict (V)
my_id, my_vector = 10, predict[10]
best_match, best_match_id, best_match_vector = -1, -1, []
similar_user_dot_predict = []
for user_id, user_vector in enumerate(predict):
  if my_id != user_id:
    similarity = np.dot(my_vector, user_vector)
    if similarity > 0:
      similar_user_dot_predict.append([similarity, user_id])
    if similarity > best_match:
      best_match = similarity
      best_match_id = user_id
      best_match_vector = user_vector
print('Best Match: {}, Best Match ID: {}'.format(best_match, best_match_id))
print(best_match_vector)

Best Match: 11.206657647538192, Best Match ID: 1002
[ 1.99601018  3.9907687   1.01745876  1.11578029  0.51994283  1.99663959
  0.28196143  0.09640423  0.98557206  0.98249856  0.99466991  0.96854965
  0.96995504  1.23320672  0.9931139   0.98740993  0.92793548  0.98753072
  0.92793548  1.02883831  0.99631135 -0.07581236]


In [134]:
similar_user_dot_predict.sort(key=lambda x:-x[0])
similar_user_dot_predict[:11]

[[11.206657647538192, 1002],
 [10.166147925502049, 908],
 [9.4938023045998, 219],
 [9.122180226429046, 617],
 [8.733606620283792, 29],
 [8.707720746510264, 613],
 [8.676011719562286, 650],
 [8.621121900656178, 189],
 [8.578859143372142, 646],
 [8.517780486573141, 657],
 [8.429277394206396, 84]]

In [135]:
arr_predict = [i[1] for i in similar_user_predict[:11]]
arr_predict.insert(0, 0)

arr_X = [i[1] for i in similar_user_X[:11]]
arr_X.insert(0, 0)

arr_R = [i[1] for i in similar_user_R[:11]]
arr_R.insert(0, 0)

arr_dot_predict = [i[1] for i in similar_user_dot_predict[:11]] # 선택(V)
arr_dot_predict.insert(0, 0)

In [136]:
arr_predict

[0, 328, 239, 252, 177, 242, 345, 931, 957, 369, 314, 950]

In [137]:
# predict// cos 유사도
for i in arr_predict:
  arr = []
  for val in df_train.iloc[i, 1:]:
    arr.append(val)
  print(arr)
print(sum([i[0] for i in similar_user_predict[:11]]))

[0.0, 2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0]
[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0]
[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0]
[0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0]
[

In [138]:
# arr_X//cos 유사도
for i in arr_X:
  arr = []
  for val in df_train.iloc[i, 1:]:
    arr.append(val)
  print(arr)
print(sum([i[0] for i in similar_user_X[:11]]))

[0.0, 2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0]
[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0]
[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0]
[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0]
[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0]
[

In [140]:
# 내적값의 크기 순서
for i in arr_dot_predict:
  arr = []
  for val in df_train.iloc[i, 1:]:
    arr.append(val)
  print(arr)

[0.0, 2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 4.0, 1.0, 0.0, 0.0, 2.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0]
[0.0, 1.0, 1.0, 1.0, 0.0, 3.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0]
[1.0, 1.0, 0.0, 0.0, 1.0, 3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0]
[0.0, 2.0, 1.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0]
[0.0, 4.0, 0.0, 1.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 1.0, 1.0, 1.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0]
[0.0, 3.0, 0.0, 0.0, 0.0, 2.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]
[

In [62]:
df.columns

Index(['관광 명소', '주소', '역사', '자연', '사진', '도보', '예술', '육상', '수상', '공중', '봄',
       '여름', '가을', '겨울', '사계절', '어린이', '청년', '중년', '노년', '혼자', '친구', '커플',
       '부모', '가족'],
      dtype='object')

# 데이터2 보류

In [ ]:
df_weather = pd.read_csv('/content/drive/MyDrive/jeju_raw_data/제주특별자치도_주제9_제주 관광을 위한 날짜별 지역 추천 데이터_매쉬업결과_(2101_2105).csv', index_col = 0, encoding = 'cp949')

In [ ]:
df_weather.columns

Index(['시도명', '읍면동명', '평균 기온', '일강수량', '최대 풍속', '업종명', '이용금액', '데이터기준일자'], dtype='object')

In [ ]:
df_weather = df_weather.reset_index()

In [ ]:
df_weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145577 entries, 0 to 145576
Data columns (total 9 columns):
 #   Column   Non-Null Count   Dtype  
---  ------   --------------   -----  
 0   일자       145577 non-null  object 
 1   시도명      145577 non-null  object 
 2   읍면동명     145577 non-null  object 
 3   평균 기온    145577 non-null  float64
 4   일강수량     145577 non-null  float64
 5   최대 풍속    145577 non-null  float64
 6   업종명      145577 non-null  object 
 7   이용금액     145577 non-null  int64  
 8   데이터기준일자  145577 non-null  object 
dtypes: float64(3), int64(1), object(5)
memory usage: 10.0+ MB


In [ ]:
set(df_weather['읍면동명'])

{'구좌읍',
 '남원읍',
 '노형동',
 '대륜동',
 '대정읍',
 '봉개동',
 '성산읍',
 '아라동',
 '안덕면',
 '애월읍',
 '예래동',
 '외도동',
 '우도면',
 '조천읍',
 '중문동',
 '추자면',
 '표선면',
 '한림읍'}